function createfigure(X1, ymatrix1, X2, Y1, X3, Y2)
%CREATEFIGURE(X1, YMATRIX1, X2, Y1, X3, Y2)
%  X1:  area x
%  YMATRIX1:  area matrix data
%  X2:  vector of x data
%  Y1:  vector of y data
%  X3:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 28-Jan-2016 17:39:03

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12);
view(axes1,[137 -90]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to area
area1 = area(X1,ymatrix1,'Parent',axes1);
set(area1(3),'FaceColor',[1 1 1]);
set(area1(2),...
    'FaceColor',[0.313725501298904 0.313725501298904 0.313725501298904]);
set(area1(1),...
    'FaceColor',[0.800000011920929 0.800000011920929 0.800000011920929]);

% Create plot
plot(X2,Y1,'LineWidth',2,'Color',[0 0 0]);

% Create plot
plot(X3,Y2,'LineWidth',4,'LineStyle','--','Color',[0 0 0]);

% Create xlabel
xlabel('Proportion of Susceptible Population','FontSize',16);

% Create ylabel
ylabel('Proportion of Infected Population','FontSize',16);

% Create textbox
annotation(figure1,'textbox',...
    [0.613063978238579 0.701517706576728 0.0617994097395634 0.0480019934204918],...
    'String',{'OPT: MAX','EQU: NO'},...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.340179108559876 0.596964586846543 0.0569065016404882 0.0438826710756924],...
    'String',['OPT: MAX',sprintf('\n'),'EQU: MAX'],...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.431911097312357 0.799985247080661 0.0507847132523058 0.0396212358052054],...
    'String',{'OPT: NO','EQU: NO'},...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1]);

